#!/bin/bash
################################################################################
# Preprocessing MR images for MR atlas based PET processing                    #
#                                   				               #
# USAGE:								       #
#	mratlpreproc paramsfn                                                  #
#                                                                              #
# This script reads a params file that includes:                               #
#	mrdir:	location of MR data					       #
#	mrfn:	file name of the MR data (currently only support dicom)	       #
#	mrid:	id name of the output 4dfp MR image			       #
#	atlpath:location of atlas target files				       #
#	atltarg:target name of the atlas (i.e. CAPIIO etc)		       #
#	roidir:	location of atlas space ROI definetion files		       #
#       roiimg: the root name of the image file that defines the ROIs.         #
#	roilist:the text file that lists ROI names and corresponding roi label #
#               in the roiimg file, it only include brain regions for regional #
#		analysis.			                               #
#									       #
#									       #
################################################################################
# Yi Su, 01/31/2014
VERSION=1.1

if [ "$1" == "--version" ]; then
    echo $VERSION
    exit 0
fi

die(){
    echo >&2 "$@"
    exit -1
}

program=`basename $0`
idstr='$Id: '$program',v '$VERSION' Mon Feb  3 09:46:46 CST 2014 suy $'
echo $idstr

if [ $# -lt 1 ]
then
	echo "Usage: $program paramsfn"
	exit -1
fi

paramsfn=$1
###############################################################################
# Read PARAMS file
source $paramsfn || die "$program ERROR: Cannot source params file $paramsfn"

# Further development will improve this program which checks the validity of
# the inputs specified in the params file

###############################################################################
# Copy ROI files

cp $roidir/${roiimg}.4dfp.* .
cp $roidir/${roilist} .

###############################################################################
# Check if MR has been pre-registered

if [[ -e "${mrdir}/${mrid}_${mrscanid}_mpr_to_${atltarg}_t4" && -e "${mrdir}/${mrid}_${mrscanid}_mpr_mskt.4dfp.img" ]]; then
    cp ${mrdir}/* .

    if [[ -z "$maskfile" ]]; then
        # populate maskfile parameter in the params file for further processing
        echo "maskfile=${mrid}_${mrscanid}_mpr_mskt.4dfp.img" >> $paramsfn
    fi
    if [[ -z "$atlt4" ]]; then
        # set atlt4 in params file
        echo "atlt4=${mrid}_${mrscanid}_mpr_to_${atltarg}_t4" >> $paramsfn
    fi
    if [[ -z "$refimg" ]]; then
        # set refimg in params file
        echo "refimg=${mrid}_${mrscanid}_mpr" >> $paramsfn
    fi


else

    ###############################################################################
    # Populate files

    dcm_to_4dfp -b ${mrid}S $mrdir/$mrfn || die "$program ERROR: DICOM to 4dfp conversion failed"

    # The MR is typically MPRAGE data acquired sagitally, will convert to
    # transverse first.
    ori=`gawk '/orientation/{print $NF}' ${mrid}S.4dfp.ifh`
    if (( ori == 2 ))
    then
        ext=( img img.rec ifh hdr )
        for (( i=0; i<4; i++ ))
        do
            cp ${mrid}S.4dfp.${ext[$i]} ${mrid}.4dfp.${ext[$i]}
        done
    elif (( ori == 3 ))
    then
        C2T_4dfp ${mrid}S ${mrid} || die "$program ERROR: C2T_4dfp ${mrid}S ${mrid} failed"
    elif (( ori == 4 ))
    then
        S2T_4dfp ${mrid}S ${mrid} || die "$program ERROR: S2T_4dfp ${mrid}S ${mrid} failed"
    else
        ERR="ERROR mratlpreproc: Wrong Orientation FLAG"
        echo $ERR
        die $program $ERR
    fi
    rm ${mrid}S.4dfp.*

    ###############################################################################
    # atlas registration
    mpr2atl_4dfp $mrid -T$atlpath/$atltarg || die "$program ERROR: atlas registration failed"

    # generate brainmask
    msktgen_4dfp $mrid -T$atlpath/$atltarg || die "$program ERROR: brainmask generation failed"

    ###############################################################################
    # Populate parameters if they aren't defined already

    if [[ -z "$maskfile" ]]; then
        # populate maskfile parameter in the params file for further processing
        echo "maskfile=${mrid}_mskt.4dfp.img" >> $paramsfn
    fi
    if [[ -z "$atlt4" ]]; then
        # set atlt4 in params file
        echo "atlt4=${mrid}_to_${atltarg}_t4" >> $paramsfn
    fi
    if [[ -z "$refimg" ]]; then
        # set refimg in params file
        echo "refimg=${mrid}" >> $paramsfn
    fi

fi
