#!/bin/bash
################################################################################
# Summarize pet atlas Based PET SUVR ROI analysis			       #
#                                   				               #
# USAGE:								       #
#	petatlsuvrsum petid roilist suvrpostfix sumpostfix	               #
#	petid:	petid is a string associated with the file name PET data in    #
#               4dfp format.						       #
#	roilist:	the text file that lists ROIs to be reported           #
#	suvrpostfix: postfix for the suvr file, standard postfix is ".suvr", it#
#		     could have extra strings, for example the postfix for an  #
#		     RSF corrected tac is "_RSF.suvr". The suvr file for a     #
#		     specific ROI and dataset would follow the naming	       #
#		     convention: ${petid}_${ROINAME}${suvrpostfix}	       #
#	sumpostfix:  postfix for the output file, standard postfix is	       #
#		     ".txt", it could have extra strings, for example the      #
#		     postfix for an RSF corrected opt is "_RSF.txt". 	       #
#		     The opt file follow the naming convention: 	       #
#				${petid}_SUVR${sumpostfix}		       #
#			and	${petid}_SUVRLR${sumpostfix}		       #
#									       #
# The output of this program is a text file that summarizes the SUVR outputs   #
################################################################################
# Yi Su, 01/29/2014

idstr='$Id: petatlsuvrsum,v 1.0 Fri Jan 31 09:40:37 CST 2014 suy $'

echo $idstr

program=`basename $0`

if [ $# -lt 4 ]
then
	echo "Usage: $program petid roilist suvrpostfix sumpostfix"
	exit -1
fi

petid=$1
roilist=$2
suvrpostfix=$3
sumpostfix=$4

optfn=${petid}_SUVR${sumpostfix}

###############################################################################
nline=`wc -l $roilist | gawk '{print $1}'`
printf "%-35s %11s %11s\n" Structure_Name NVox SUVR > $optfn
for (( i=1; i<=$nline; i++ ))
do
	ROI=`gawk 'NR=='$i' {print $1}'  $roilist`
	fn=${petid}_${ROI}${suvrpostfix}
	if [ -e $fn ]
	then
		nv=`gawk 'NR==3 {print $2}'  $fn`
		suvr=`gawk 'NR==3 {print $3}'  $fn`
	else
		nv=0
		suvr=0
	fi
	printf "%-35s %11d %11.4f\n" ${ROI} $nv $suvr >> $optfn
done
