#!/bin/bash
###################--------------------------------------------------------------
# The purpose of this program is to create .info file based on the dynamic 4dfp file
# in the order of: start time, frame time, duration, decay correction factor, frame number
###################--------------------------------------------------------------
# Inputs to the program
#
# $1: 4dfp PET file name (*.4dfp.img) assuming the frame duration and decay correction info is in the .rec file
#
###################--------------------------------------------------------------
# Yi Su, 07/18/2016

idstr='$Id: PETinfo,v 1.2 Mon Jul 18 13:17:44 CDT 2016 suy Exp $'
echo $idstr

                                                            
petfstr=$1
petdir=`dirname $petfstr`
petname=`basename $petfstr`
petroot=${petname%%.*}
format=$2
if [ $# -gt 2 ]
then
	(( delay=$3*60 ))
else
	(( delay=0 ))
fi

frames=`gawk '/matrix size \[4\]/ {print $5}' $petdir"/"$petroot".4dfp.ifh"`
if [ -e  $petroot".info" ]
then
	rm $petroot".info"
fi
touch $petroot".info"

fd=`gawk '/Frame_1 / {print $2/1000}' $petdir"/"$petroot".4dfp.img.rec"`
dc=`gawk '/Frame_1 / {print $7}' $petdir"/"$petroot".4dfp.img.rec"`
if (( $format == 1 ))
then
	st0=`gawk '/Frame_1 / {print $4/1000}' $petdir"/"$petroot".4dfp.img.rec"`
elif (( $format == 0 ))
then
	t=`gawk '/Frame_1 / {print $3}' $petdir"/"$petroot".4dfp.img.rec"`
	st0=$(echo "scale=8; $t-$fd/2" | bc)	
elif (( $format == 2 ))
then
	t=`gawk '/Frame_1 / {print $3}' $petdir"/"$petroot".4dfp.img.rec"`
	st0=$(echo "scale=8; $t-$fd/2" | bc)
elif (( $format == 5 ))
then
	t=`gawk '/Frame_1 / {print $3}' $petdir"/"$petroot".4dfp.img.rec"`
	st0=$(echo "scale=8; $t-$fd/2" | bc)
fi


for (( f=1; f<=$frames; f++ ))
do
	fd=`gawk '/Frame_'$f' / {print $2/1000}' $petdir"/"$petroot".4dfp.img.rec"`
	dc=`gawk '/Frame_'$f' / {print $7}' $petdir"/"$petroot".4dfp.img.rec"`
	if (( $format == 1 ))
	then
		st=`gawk '/Frame_'$f' / {print $4/1000}' $petdir"/"$petroot".4dfp.img.rec"`
		t=$(echo "scale=8; $st+$fd/2" | bc)
	elif (( $format == 0 ))
	then
		t=`gawk '/Frame_'$f' / {print $3}' $petdir"/"$petroot".4dfp.img.rec"`
		st=$(echo "scale=8; $t-$fd/2" | bc)	
	elif (( $format == 2 ))
	then
		t=`gawk '/Frame_'$f' / {print $3}' $petdir"/"$petroot".4dfp.img.rec"`
		st=$(echo "scale=8; $t-$fd/2" | bc)
	elif (( $format == 5 ))
	then
		t=`gawk '/Frame_'$f' / {print $3}' $petdir"/"$petroot".4dfp.img.rec"`
		st=$(echo "scale=8; $t-$fd/2" | bc)
	fi
	st=$(echo "scale=8; $st-$st0+$delay" |bc)
	t=$(echo "scale=8; $t-$st0+$delay" |bc)	
	printf '%f\t%f\t%f\t%f\t%d\n' $st $t $fd $dc $f >> $petroot".info"
done

exit 0
