#!/bin/bash
################################################################################
# Generating Report for Logan Reference Region Analysis			       #
#                                                                              #
# USAGE:								       #
#	petloganrep paramsfn                                        	       #
#                                                                              #
################################################################################
# Yi Su, 01/08/2014

idstr='$Id: petloganrep,v 1.1 Mon Feb  3 09:45:58 CST 2014 suy $'

echo $idstr

program=`basename $0`

if [ $# -lt 1 ]
then
	echo "Usage: $program paramsfn"
	exit -1
fi

paramsfn=$1
###############################################################################
# Read PARAMS file
source $paramsfn

# Further development will improve this program which checks the validity of
# the inputs specified in the params file

###############################################################################
if (( FS == 1 ))
then
	fslogansum $petid $roisfn .mdl .txt
	if (( rsfflag == 1 ))
	then
		fslogansum $petid $roisfn _RSF.mdl _RSF.txt
	fi
	if (( pvc2cflag == 1 ))
	then
		fslogansum $petid $roisfn _PVC2C.mdl _PVC2C.txt
	fi
	
fi

if (( tgflag == 1 ))
then
	roilogansum $petid $roilist .mdl .txt
fi

if (( tgflag == 2 ))
then
	roilogansum $petid $roilist .mdl .txt
fi
###############################################################################
# Additional ROI target based processing will be included in the future



###############################################################################

exit $?
