#!/bin/bash
################################################################################
# Generating Report for Logan Reference Region Analysis			       #
#                                                                              #
# USAGE:								       #
#	petloganrep paramsfn                                        	       #
#                                                                              #
################################################################################
# Yi Su, 01/08/2014
VERSION=1.1

if [ "$1" == "--version" ]; then
    echo $VERSION
    exit 0
fi

die(){
    echo >&2 "$@"
    exit -1
}

program=`basename $0`
idstr='$Id: '$program',v '$VERSION' Mon Feb  3 09:45:58 CST 2014 suy $'
echo $idstr

if [ $# -lt 1 ]
then
	echo "Usage: $program paramsfn"
	exit -1
fi

paramsfn=$1
###############################################################################
# Read PARAMS file
source $paramsfn

# Further development will improve this program which checks the validity of
# the inputs specified in the params file

###############################################################################
if (( FS == 1 ))
then
	fslogansum $petid $roisfn .mdl .txt || die "$program ERROR: fslogansum $petid $roisfn .mdl .txt failed"
	if (( rsfflag == 1 ))
	then
		fslogansum $petid $roisfn _RSF.mdl _RSF.txt || die "$program ERROR: fslogansum $petid $roisfn _RSF.mdl _RSF.txt failed"
	fi
	if (( pvc2cflag == 1 ))
	then
		fslogansum $petid $roisfn _PVC2C.mdl _PVC2C.txt || die "$program ERROR: fslogansum $petid $roisfn _PVC2C.mdl _PVC2C.txt failed"
	fi

fi

if (( tgflag == 1 ))
then
	roilogansum $petid $roilist .mdl .txt || die "$program ERROR: roilogansum $petid $roilist .mdl .txt failed"
fi

if (( tgflag == 2 ))
then
	roilogansum $petid $roilist .mdl .txt || die "$program ERROR: roilogansum $petid $roilist .mdl .txt failed"
fi
###############################################################################
# Additional ROI target based processing will be included in the future



###############################################################################
