#!/bin/bash
################################################################################
# PET roi SUVR calculation						       #
#                                   				               #
# USAGE:								       #
#	petsuvr paramsfn	                                               #
#                                                                              #
# This script reads a params file that includes:                               #
#	petid:	petid is a string associated with the file name PET data in    #
#               4dfp format.						       #
#	roilist:the text file that lists ROI names                             #
#	rsfflag: whether RSF PVC is performed				       #
#	pvc2cflag: whether PVC2C is performed				       #
#	sf:	model starting frame					       #
#	ef:	model ending frame					       #
#									       #
#									       #
# The output of this program is SUVR for each ROI and SUVR images in target    #
# space									       #
################################################################################
# Yi Su, 01/07/2014
VERSION=1.0

if [ "$1" == "--version" ]; then
    echo $VERSION
    exit 0
fi

die(){
    echo >&2 "$@"
    exit -1
}

program=`basename $0`
idstr='$Id: '$program',v '$VERSION' Fri Jan 31 09:40:22 CST 2014 suy $'
echo $idstr

if [ $# -lt 1 ]
then
	echo "Usage: $program paramsfn"
	exit -1
fi

paramsfn=$1
###############################################################################
# Read PARAMS file
source $paramsfn || die "$program ERROR: Cannot source params file $paramsfn"

# Further development will improve this program which checks the validity of
# the inputs specified in the params file

###############################################################################

NROI=`wc -l $roilist | gawk '{print $1}'`
for (( i=1; i<=$NROI; i++ ))
do
	label=`gawk 'NR=='$i' {print $1}' $roilist`
	suvrROI ${petid}_REF.tac ${petid}_${label}.tac $label $sf $ef ${petid}_${label}.suvr || die "$program ERROR: suvrROI ${petid}_REF.tac ${petid}_${label}.tac $label $sf $ef ${petid}_${label}.suvr failed"

	if (( rsfflag == 1 ))
	then
		suvrROI ${petid}_REF_RSF.tac ${petid}_${label}_RSF.tac $label $sf $ef ${petid}_${label}_RSF.suvr || die "$program ERROR: suvrROI ${petid}_REF_RSF.tac ${petid}_${label}_RSF.tac $label $sf $ef ${petid}_${label}_RSF.suvr failed"
	fi
	if (( pvc2cflag == 1 ))
	then
		suvrROI ${petid}_REF_PVC2C.tac ${petid}_${label}_PVC2C.tac $label $sf $ef ${petid}_${label}_PVC2C.suvr || die "$program ERROR: suvrROI ${petid}_REF_PVC2C.tac ${petid}_${label}_PVC2C.tac $label $sf $ef ${petid}_${label}_PVC2C.suvr failed"
	fi
done

ref=`gawk 'NR==2 {print $4}' ${petid}_REF.tac`
if (( $(bc <<< "$ref == 0" ) == 1 ))
then
    die "$program ERROR: ref=${ref}. Cannot calculate 1/ref."
fi
scf=$(echo "scale=8; 1/$ref" | bc)

ext=( img img.rec ifh hdr )
for (( i=0; i<4; i++ ))
do
	cp ${petid}_on_roi.4dfp.${ext[$i]} ${petid}_SUVR.4dfp.${ext[$i]}
done
scale_4dfp ${petid}_SUVR $scf || die "$program ERROR: scale_4dfp ${petid}_SUVR $scf failed"
gauss_4dfp ${petid}_SUVR 0.8 || die "$program ERROR: gauss_4dfp ${petid}_SUVR 0.8 failed"

