#!/bin/bash
################################################################################
# Generating Report for SUVR Analysis			       #
#                                                                              #
# USAGE:								       #
#	petsuvrrep paramsfn                                        	       #
#                                                                              #
################################################################################
# Yi Su, 01/08/2014

idstr='$Id: petsuvrrep,v 1.0 Fri Jan 31 09:39:59 CST 2014 suy $'

echo $idstr

program=`basename $0`

if [ $# -lt 1 ]
then
	echo "Usage: $program paramsfn"
	exit -1
fi

paramsfn=$1
###############################################################################
# Read PARAMS file
source $paramsfn

# Further development will improve this program which checks the validity of
# the inputs specified in the params file

###############################################################################
if (( FS == 1 ))
then
	fssuvrsum $petid $roisfn .suvr .txt
	if (( rsfflag == 1 ))
	then
		fssuvrsum $petid $roisfn _RSF.suvr _RSF.txt
	fi
	if (( pvc2cflag == 1 ))
	then
		fssuvrsum $petid $roisfn _PVC2C.suvr _PVC2C.txt
	fi	
fi


###############################################################################
# Additional ROI target based processing will be included in the future

if (( tgflag == 1 ))
then
	petatlsuvrsum $petid $roilist .suvr .txt
fi


###############################################################################

exit $?
