#!/bin/bash
################################################################################
# Generating Report for SUVR Analysis			       #
#                                                                              #
# USAGE:								       #
#	petsuvrrep paramsfn                                        	       #
#                                                                              #
################################################################################
# Yi Su, 01/08/2014
VERSION=1.1

if [ "$1" == "--version" ]; then
    echo $VERSION
    exit 0
fi

die(){
    echo >&2 "$@"
    exit -1
}

program=`basename $0`
idstr='$Id: '$program',v '$VERSION' Mon Feb  3 09:46:28 CST 2014 suy $'
echo $idstr

if [ $# -lt 1 ]
then
	echo "Usage: $program paramsfn"
	exit -1
fi

paramsfn=$1
###############################################################################
# Read PARAMS file
source $paramsfn || die "$program ERROR: Cannot source params file $paramsfn"

# Further development will improve this program which checks the validity of
# the inputs specified in the params file

###############################################################################
if (( FS == 1 ))
then
	fssuvrsum $petid $roisfn .suvr .txt || die "$program ERROR: fssuvrsum $petid $roisfn .suvr .txt failed"
	if (( rsfflag == 1 ))
	then
		fssuvrsum $petid $roisfn _RSF.suvr _RSF.txt || die "$program ERROR: fssuvrsum $petid $roisfn _RSF.suvr _RSF.txt failed"
	fi
	if (( pvc2cflag == 1 ))
	then
		fssuvrsum $petid $roisfn _PVC2C.suvr _PVC2C.txt || die "$program ERROR: fssuvrsum $petid $roisfn _PVC2C.suvr _PVC2C.txt failed"
	fi
fi


###############################################################################
# Additional ROI target based processing will be included in the future

if (( tgflag == 1 ))
then
	petatlsuvrsum $petid $roilist .suvr .txt || die "$program ERROR: petatlsuvrsum $petid $roilist .suvr .txt failed"
fi

if (( tgflag == 2 ))
then
	petatlsuvrsum $petid $roilist .suvr .txt || die "$program ERROR: petatlsuvrsum $petid $roilist .suvr .txt failed"
fi
###############################################################################
