#!/bin/bash
################################################################################
# Preprocessing FREESURFER output files for PET ROI analysis                   #
#                                   				               #
# USAGE:								       #
#	fspreproc paramsfn                                                     #
#                                                                              #
# This script reads a params file that includes:                               #
#	fsdir: location of FREESURFER mgz out files			       #
#	wmparc:	FREESURFER segmentation file (wmparc.mgz)		       #
#	t1: FREESURFER MR file (t1.mgz or orig.mgz)			       #
#       rsfmask:the root name of the image file that defines the RSF PVC       #
#		correction mask						       #
#	rsflist:the text file that lists ROI names and corresponding roi label #
#		in the rsfmask file					       #
#	roilist:the text file that lists ROI names and corresponding roi label #
#               in the rsfmask file                                            #
#	fwhm:	PET resolution in mm					       #
#	rsfflag: whether RSF PVC will be performed			       #
#	pvc2cflag: whether PVC2C will be performed			       #
#									       #
#									       #
# The output of this program is a series of TAC curves			       #
################################################################################
# Yi Su, 12/24/2013
VERSION=1.0

if [ "$1" == "--version" ]; then
    echo $VERSION
    exit 0
fi

die(){
    echo >&2 "$@"
    exit -1
}

program=`basename $0`
idstr='$Id: '$program',v '$VERSION' 2013/12/24 18:07:48 suy Exp $'
echo $idstr

if [ $# -lt 1 ]
then
	echo "Usage: $program paramsfn"
	exit -1
fi

paramsfn=$1
###############################################################################
# Read PARAMS file
source $paramsfn || die "$program ERROR: Cannot source params file $paramsfn"

# Further development will improve this program which checks the validity of
# the inputs specified in the params file

###############################################################################
cp $fsdir/$t1 .
cp $fsdir/$wmparc .

mgzto4dfp $t1 || die "$program ERROR: mgzto4dfp $t1 failed"
mgzto4dfp $wmparc || die "$program ERROR: mgzto4dfp $wmparc failed"

mrroot=${t1%.*}
mrroot=${mrroot}001
fsfroot=${fsfname%.*}
fsfroot=${fsfroot}001

###############################################################################
# Processing freesurfer rois, whole head roi, and prepare for roi analysis
if [ ! -e ${mrroot}"_g9.4dfp.img" ]
then
	gauss_4dfp ${mrroot} 0.9 || die "$program ERROR: gauss_4dfp ${mrroot} 0.9 failed"
fi
maskimg_4dfp -v1 -t15 T1001_g9  T1001_g9 Head_Mask || die "$program ERROR: maskimg_4dfp -v1 -t15 T1001_g9  T1001_g9 Head_Mask failed"
PreprocessRSFtest2 $fsfroot Head_Mask  RSFMask ROIlist.txt $fslut || die "$program ERROR: PreprocessRSFtest2 $fsfroot Head_Mask  RSFMask ROIlist.txt $fslut failed"

