#!/bin/bash
################################################################################
# ROI target preprocessing. 						       #
#                                                                              #
# USAGE:								       #
#	targpreproc paramsfn                                                   #
#                                                                              #
################################################################################
# Yi Su, 01/08/2014

idstr='$Id: targpreproc,v 1.0 Fri Jan 31 09:41:08 CST 2014 suy $'

echo $idstr

program=`basename $0`

if [ $# -lt 1 ]
then
	echo "Usage: $program paramsfn"
	exit -1
fi

paramsfn=$1
###############################################################################
# Read PARAMS file
source $paramsfn

# Further development will improve this program which checks the validity of
# the inputs specified in the params file

###############################################################################
if (( FS == 1 ))
then
	fspreproc $paramsfn
fi

if (( tgflag == 1 ))
then
	petatlpreproc $paramsfn
fi

###############################################################################
# Additional ROI target based processing is under development

exit 0
