#!/bin/bash
################################################################################
# ROI target preprocessing. 						       #
#                                                                              #
# USAGE:								       #
#	targpreproc paramsfn                                                   #
#                                                                              #
################################################################################
# Yi Su, 01/08/2014
VERSION=1.1

if [ "$1" == "--version" ]; then
    echo $VERSION
    exit 0
fi

die(){
    echo >&2 "$@"
    exit -1
}

program=`basename $0`
idstr='$Id: '$program',v '$VERSION' Mon Feb  3 09:46:36 CST 2014 suy $'
echo $idstr

if [ $# -lt 1 ]
then
	echo "Usage: $program paramsfn"
	exit -1
fi

paramsfn=$1
###############################################################################
# Read PARAMS file
source $paramsfn || die "$program ERROR: Cannot source params file $paramsfn"

# Further development will improve this program which checks the validity of
# the inputs specified in the params file

###############################################################################

# FREESURFER based processing. The preprocessing step converts freesurfer
# files into 4dfp format, and prepares for ROI analysis.
if (( FS == 1 ))
then
	fspreproc $paramsfn || die "$program ERROR: fspreproc $paramsfn failed"
fi

# PET ATLAS based processing. The preprocessing step populates PET atlas
# template image and ROI definetion files in the PET atlas space and prepare
# for ROI analysis.
if (( tgflag == 1 ))
then
	petatlpreproc $paramsfn || die "$program ERROR: petatlpreproc $paramsfn failed"
fi

# MR ATLAS based processing. The preprocessing step converts MR images to
# 4dfp format and register it to atlas space. The ROIs are defined in the
# atlas space. It can be standard template ROIs or manually defined ROIs.
if (( tgflag == 2 ))
then
	mratlpreproc $paramsfn || die "$program ERROR: mratlpreproc $paramsfn failed"
fi
###############################################################################
# Additional ROI target based processing is under development

