#!/bin/bash
################################################################################
# ROI target preprocessing. 						       #
#                                                                              #
# USAGE:								       #
#	targpreproc paramsfn                                                   #
#                                                                              #
################################################################################
# Yi Su, 01/08/2014

idstr='$Id: targpreproc,v 1.1 Mon Feb  3 09:46:36 CST 2014 suy $'

echo $idstr

program=`basename $0`

if [ $# -lt 1 ]
then
	echo "Usage: $program paramsfn"
	exit -1
fi

paramsfn=$1
###############################################################################
# Read PARAMS file
source $paramsfn

# Further development will improve this program which checks the validity of
# the inputs specified in the params file

###############################################################################

# FREESURFER based processing. The preprocessing step converts freesurfer
# files into 4dfp format, and prepares for ROI analysis.
if (( FS == 1 ))
then
	fspreproc $paramsfn
fi

# PET ATLAS based processing. The preprocessing step populates PET atlas
# template image and ROI definetion files in the PET atlas space and prepare
# for ROI analysis.
if (( tgflag == 1 ))
then
	petatlpreproc $paramsfn
fi

# MR ATLAS based processing. The preprocessing step converts MR images to 
# 4dfp format and register it to atlas space. The ROIs are defined in the 
# atlas space. It can be standard template ROIs or manually defined ROIs.
if (( tgflag == 2 ))
then
	mratlpreproc $paramsfn
fi
###############################################################################
# Additional ROI target based processing is under development

exit 0
